### PR TITLE
Modified it to use Composition API

### PR DESCRIPTION
**Pull request by ZachHandley**
As titled, I moved it to composition api so it won't error anymore in TS projects. Rewrote the props, had to move some defaults to the prop defaults but I doubt anyone will have a hard time finding them. Hopefully this helps.

### CODE REVIEW

**Comment by Toverbal** [comment]
Hi Zach, I am in the process of transforming a small app to ts and it uses the confetti explosion component. I noticed that it indeed didn't work and so I came across this PR. I figured it would help me getting rid of the errors in my refactor task. I'm still quite novice on ts, so I'm not sure what is wrong, but I tried to build your repo and I stumbled upon two errors. When pulling your repo and running a build, the first error is:
`[!] (plugin vue) TypeError: Cannot read properties of undefined (reading 'line')`

This is pretty cryptic, but after commenting out parts of the code I figured out it was because of the colors property.
```vue
  colors: {
    type: Array<string>,
    default: ["#FFC700", "#FF0000", "#2E3191", "#41BBC7"],
  },
```
Changing the array definition to 
```
type: Array as PropType<string[]>,
```
seems to fix that problem.

Only then when I try to build I get the following error:
```
[!] (plugin rpt2) Error: ./src/ConfettiExplosion.vue?vue&type=script&setup=true&lang.ts(328,19): semantic error TS7006: Parameter 'el' implicitly has an 'any' type.
```

Searching for the error, I found out it is not on line 328, but on line 319:
```
:ref="(el: any) => setItemRef(el, degree)"
```

I tried everything, but I can't seem to get this working. This is probably because of my novice knowledge of ts, but you might be able to fix it or even better: tell me what I am doing wrong 😅

Thanks!

**Comment by ZachHandley** [comment]
@Toverbal I have updated the code to fix that issue, replaced it with `withDefaults` instead, should work fine now, let me know if you have any other issues!

**Comment by Toverbal** [comment]
@ZachHandley hi, it seems that this partly fixes the problems, the color property now works, though I had to set noUnusedLocals in tsconfig.json to false, else it would nag about semantic error TS6196: 'IConfettiProps' is declared but never used. 

The other problem still exists, I cannot create a build, because it gives an error:
```
: semantic error TS7006: Parameter 'el' implicitly has an 'any' type.
```
on this line:
```
:ref="(el: any) => setItemRef(el, degree)"
```

I'm running npm run build. That is correct, right? 😅 Thanks for your efforts!

**Comment by ZachHandley** [comment]
Are you on the ESNext typescript?

**Comment by Toverbal** [comment]
@ZachHandley if you mean the compilerOptions target and module in tsconfig.json, then yes.
```
    "compilerOptions": {
        "target": "esnext",
        "module": "esnext",
```

I'm not sure why it doesn't work. Just to be sure: clone repo, npm install, npm run build should be enough to build the project, right?

**Pull request closed without merging**
